### ISSUE TITLE
🐛 The 'pyinstaller' distribution was not found and is required by pros-cli

### ISSUE THREAD

**Issue by BNH440** [purduesigbots/pros-cli#247]
#### Expected Behavior:
The `prosv5` command should run normally.

#### Actual Behavior:
The `prosv5`command fails with this error:

```
The 'pyinstaller' distribution was not found and is required by pros-cli
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pros/cli/main.py", line 63, in main
    .format(version = get_version()), ctx_obj)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pros/common/utils.py", line 30, in get_version
    import pkg_resources
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyinstaller' distribution was not found and is required by pros-cli
```
#### Steps to reproduce:
Install CLI version 3.4.1 using homebrew, then run `prosv5`

#### System information:
Operating System: MacOS Ventura 13.0.1 on Apple Silicon

PROS Version: CLI version 3.4.1

**Comment by kunwarsahni01** [comment]
Okay looks like the pyinstaller dependency was missing from the homebrew formula, so I went ahead and added it, try reinstalling and pulling again and it should work now.

**Comment by BNH440** [comment]
Thanks for the help, it looks like there's a new error now:

```
The 'macholib>=1.8; sys_platform == "darwin"' distribution was not found and is required by pyinstaller
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pros/cli/main.py", line 63, in main
    .format(version = get_version()), ctx_obj)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pros/common/utils.py", line 30, in get_version
    import pkg_resources
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/homebrew/Cellar/pros-cli/3.4.1/libexec/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'macholib>=1.8; sys_platform == "darwin"' distribution was not found and is required by pyinstaller
```

**Comment by kunwarsahni01** [comment]
Hmm, okay looks to be a spiraling dependency issue, let me see what I can do.

**Comment by kunwarsahni01** [comment]
Alright looks like I have the right combination of dependencies now, give it a go now.

**Comment by BNH440** [comment]
Works now, thanks for your help!
